# Generated by Django 4.2.6 on 2023-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scientific_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
